version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend

  - package-ecosystem: npm
    directory: /web-editor-next
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend
