// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/synapse/v1/hub.proto

package synapsev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED        Protocol = 0
	Protocol_PROTOCOL_OPENAI_CHAT        Protocol = 1
	Protocol_PROTOCOL_ANTHROPIC_MESSAGES Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_OPENAI_CHAT",
		2: "PROTOCOL_ANTHROPIC_MESSAGES",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED":        0,
		"PROTOCOL_OPENAI_CHAT":        1,
		"PROTOCOL_ANTHROPIC_MESSAGES": 2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_synapse_v1_hub_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_synapse_v1_hub_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{0}
}

type SakerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SakerMessage_Hello
	//	*SakerMessage_Heartbeat
	//	*SakerMessage_Chunk
	//	*SakerMessage_Done
	//	*SakerMessage_Error
	//	*SakerMessage_ToolEvent
	//	*SakerMessage_Pong
	Payload       isSakerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SakerMessage) Reset() {
	*x = SakerMessage{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SakerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SakerMessage) ProtoMessage() {}

func (x *SakerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SakerMessage.ProtoReflect.Descriptor instead.
func (*SakerMessage) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{0}
}

func (x *SakerMessage) GetPayload() isSakerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SakerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*SakerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *SakerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*SakerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *SakerMessage) GetChunk() *ChatChunk {
	if x != nil {
		if x, ok := x.Payload.(*SakerMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *SakerMessage) GetDone() *ChatDone {
	if x != nil {
		if x, ok := x.Payload.(*SakerMessage_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *SakerMessage) GetError() *ChatError {
	if x != nil {
		if x, ok := x.Payload.(*SakerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *SakerMessage) GetToolEvent() *ToolEvent {
	if x != nil {
		if x, ok := x.Payload.(*SakerMessage_ToolEvent); ok {
			return x.ToolEvent
		}
	}
	return nil
}

func (x *SakerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*SakerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isSakerMessage_Payload interface {
	isSakerMessage_Payload()
}

type SakerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type SakerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type SakerMessage_Chunk struct {
	Chunk *ChatChunk `protobuf:"bytes,3,opt,name=chunk,proto3,oneof"`
}

type SakerMessage_Done struct {
	Done *ChatDone `protobuf:"bytes,4,opt,name=done,proto3,oneof"`
}

type SakerMessage_Error struct {
	Error *ChatError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type SakerMessage_ToolEvent struct {
	ToolEvent *ToolEvent `protobuf:"bytes,6,opt,name=tool_event,json=toolEvent,proto3,oneof"`
}

type SakerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,7,opt,name=pong,proto3,oneof"`
}

func (*SakerMessage_Hello) isSakerMessage_Payload() {}

func (*SakerMessage_Heartbeat) isSakerMessage_Payload() {}

func (*SakerMessage_Chunk) isSakerMessage_Payload() {}

func (*SakerMessage_Done) isSakerMessage_Payload() {}

func (*SakerMessage_Error) isSakerMessage_Payload() {}

func (*SakerMessage_ToolEvent) isSakerMessage_Payload() {}

func (*SakerMessage_Pong) isSakerMessage_Payload() {}

type HubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HubMessage_HelloAck
	//	*HubMessage_Request
	//	*HubMessage_Cancel
	//	*HubMessage_Shutdown
	//	*HubMessage_Ping
	Payload       isHubMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{1}
}

func (x *HubMessage) GetPayload() isHubMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HubMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *HubMessage) GetRequest() *ChatRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *HubMessage) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *HubMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *HubMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isHubMessage_Payload interface {
	isHubMessage_Payload()
}

type HubMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type HubMessage_Request struct {
	Request *ChatRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type HubMessage_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

type HubMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,4,opt,name=shutdown,proto3,oneof"`
}

type HubMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*HubMessage_HelloAck) isHubMessage_Payload() {}

func (*HubMessage_Request) isHubMessage_Payload() {}

func (*HubMessage_Cancel) isHubMessage_Payload() {}

func (*HubMessage_Shutdown) isHubMessage_Payload() {}

func (*HubMessage_Ping) isHubMessage_Payload() {}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstanceId      string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	SandboxId       string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BridgeVersion   string                 `protobuf:"bytes,4,opt,name=bridge_version,json=bridgeVersion,proto3" json:"bridge_version,omitempty"`
	Models          []string               `protobuf:"bytes,5,rep,name=models,proto3" json:"models,omitempty"`
	MaxConcurrent   int32                  `protobuf:"varint,6,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	AuthToken       string                 `protobuf:"bytes,7,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PrimaryProtocol Protocol               `protobuf:"varint,9,opt,name=primary_protocol,json=primaryProtocol,proto3,enum=synapse.v1.Protocol" json:"primary_protocol,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Hello) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetBridgeVersion() string {
	if x != nil {
		return x.BridgeVersion
	}
	return ""
}

func (x *Hello) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Hello) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *Hello) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *Hello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Hello) GetPrimaryProtocol() Protocol {
	if x != nil {
		return x.PrimaryProtocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

type HelloAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Accepted         bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AssignedNodeId   string                 `protobuf:"bytes,3,opt,name=assigned_node_id,json=assignedNodeId,proto3" json:"assigned_node_id,omitempty"`
	ServerTimeUnixNs int64                  `protobuf:"varint,4,opt,name=server_time_unix_ns,json=serverTimeUnixNs,proto3" json:"server_time_unix_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HelloAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HelloAck) GetAssignedNodeId() string {
	if x != nil {
		return x.AssignedNodeId
	}
	return ""
}

func (x *HelloAck) GetServerTimeUnixNs() int64 {
	if x != nil {
		return x.ServerTimeUnixNs
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixNanos     int64                  `protobuf:"varint,1,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	InFlight      int32                  `protobuf:"varint,2,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemRssBytes   uint64                 `protobuf:"varint,4,opt,name=mem_rss_bytes,json=memRssBytes,proto3" json:"mem_rss_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *Heartbeat) GetInFlight() int32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *Heartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemRssBytes() uint64 {
	if x != nil {
		return x.MemRssBytes
	}
	return 0
}

type ChatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId          string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Protocol          Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=synapse.v1.Protocol" json:"protocol,omitempty"`
	Payload           []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers           map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeadlineUnixNanos int64                  `protobuf:"varint,7,opt,name=deadline_unix_nanos,json=deadlineUnixNanos,proto3" json:"deadline_unix_nanos,omitempty"`
	RequestedModel    string                 `protobuf:"bytes,8,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{5}
}

func (x *ChatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ChatRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *ChatRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ChatRequest) GetDeadlineUnixNanos() int64 {
	if x != nil {
		return x.DeadlineUnixNanos
	}
	return 0
}

func (x *ChatRequest) GetRequestedModel() string {
	if x != nil {
		return x.RequestedModel
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	GraceSeconds  int32                  `protobuf:"varint,2,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{7}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Shutdown) GetGraceSeconds() int32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixNanos     int64                  `protobuf:"varint,1,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixNanos     int64                  `protobuf:"varint,1,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{9}
}

func (x *Pong) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SakerEventId  string                 `protobuf:"bytes,4,opt,name=saker_event_id,json=sakerEventId,proto3" json:"saker_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{10}
}

func (x *ChatChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChatChunk) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ChatChunk) GetSakerEventId() string {
	if x != nil {
		return x.SakerEventId
	}
	return ""
}

type ChatDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatDone) Reset() {
	*x = ChatDone{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDone) ProtoMessage() {}

func (x *ChatDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDone.ProtoReflect.Descriptor instead.
func (*ChatDone) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{11}
}

func (x *ChatDone) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatDone) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatDone) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ChatError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HttpStatus    int32                  `protobuf:"varint,4,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatError) Reset() {
	*x = ChatError{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatError) ProtoMessage() {}

func (x *ChatError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatError.ProtoReflect.Descriptor instead.
func (*ChatError) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{12}
}

func (x *ChatError) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ChatError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatError) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

type ToolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent) Reset() {
	*x = ToolEvent{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent) ProtoMessage() {}

func (x *ToolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent.ProtoReflect.Descriptor instead.
func (*ToolEvent) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{13}
}

func (x *ToolEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ToolEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ToolEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     uint64                 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint64                 `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      uint64                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	Model            string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_hub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_hub_proto_rawDescGZIP(), []int{14}
}

func (x *Usage) GetPromptTokens() uint64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() uint64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() uint64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Usage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_proto_synapse_v1_hub_proto protoreflect.FileDescriptor

const file_proto_synapse_v1_hub_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/synapse/v1/hub.proto\x12\n" +
	"synapse.v1\"\xe5\x02\n" +
	"\fSakerMessage\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.synapse.v1.HelloH\x00R\x05hello\x125\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.synapse.v1.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\x05chunk\x18\x03 \x01(\v2\x15.synapse.v1.ChatChunkH\x00R\x05chunk\x12*\n" +
	"\x04done\x18\x04 \x01(\v2\x14.synapse.v1.ChatDoneH\x00R\x04done\x12-\n" +
	"\x05error\x18\x05 \x01(\v2\x15.synapse.v1.ChatErrorH\x00R\x05error\x126\n" +
	"\n" +
	"tool_event\x18\x06 \x01(\v2\x15.synapse.v1.ToolEventH\x00R\ttoolEvent\x12&\n" +
	"\x04pong\x18\a \x01(\v2\x10.synapse.v1.PongH\x00R\x04pongB\t\n" +
	"\apayload\"\x92\x02\n" +
	"\n" +
	"HubMessage\x123\n" +
	"\thello_ack\x18\x01 \x01(\v2\x14.synapse.v1.HelloAckH\x00R\bhelloAck\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x17.synapse.v1.ChatRequestH\x00R\arequest\x123\n" +
	"\x06cancel\x18\x03 \x01(\v2\x19.synapse.v1.CancelRequestH\x00R\x06cancel\x122\n" +
	"\bshutdown\x18\x04 \x01(\v2\x14.synapse.v1.ShutdownH\x00R\bshutdown\x12&\n" +
	"\x04ping\x18\x05 \x01(\v2\x10.synapse.v1.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\x99\x03\n" +
	"\x05Hello\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0ebridge_version\x18\x04 \x01(\tR\rbridgeVersion\x12\x16\n" +
	"\x06models\x18\x05 \x03(\tR\x06models\x12%\n" +
	"\x0emax_concurrent\x18\x06 \x01(\x05R\rmaxConcurrent\x12\x1d\n" +
	"\n" +
	"auth_token\x18\a \x01(\tR\tauthToken\x125\n" +
	"\x06labels\x18\b \x03(\v2\x1d.synapse.v1.Hello.LabelsEntryR\x06labels\x12?\n" +
	"\x10primary_protocol\x18\t \x01(\x0e2\x14.synapse.v1.ProtocolR\x0fprimaryProtocol\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\bHelloAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12(\n" +
	"\x10assigned_node_id\x18\x03 \x01(\tR\x0eassignedNodeId\x12-\n" +
	"\x13server_time_unix_ns\x18\x04 \x01(\x03R\x10serverTimeUnixNs\"\x8c\x01\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x01 \x01(\x03R\tunixNanos\x12\x1b\n" +
	"\tin_flight\x18\x02 \x01(\x05R\binFlight\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\"\n" +
	"\rmem_rss_bytes\x18\x04 \x01(\x04R\vmemRssBytes\"\x89\x03\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x120\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x14.synapse.v1.ProtocolR\bprotocol\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12>\n" +
	"\aheaders\x18\x06 \x03(\v2$.synapse.v1.ChatRequest.HeadersEntryR\aheaders\x12.\n" +
	"\x13deadline_unix_nanos\x18\a \x01(\x03R\x11deadlineUnixNanos\x12'\n" +
	"\x0frequested_model\x18\b \x01(\tR\x0erequestedModel\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"G\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12#\n" +
	"\rgrace_seconds\x18\x02 \x01(\x05R\fgraceSeconds\"%\n" +
	"\x04Ping\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x01 \x01(\x03R\tunixNanos\"%\n" +
	"\x04Pong\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x01 \x01(\x03R\tunixNanos\"\x83\x01\n" +
	"\tChatChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12$\n" +
	"\x0esaker_event_id\x18\x04 \x01(\tR\fsakerEventId\"w\n" +
	"\bChatDone\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x05usage\x18\x02 \x01(\v2\x11.synapse.v1.UsageR\x05usage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"y\n" +
	"\tChatError\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vhttp_status\x18\x04 \x01(\x05R\n" +
	"httpStatus\"R\n" +
	"\tToolEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x92\x01\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x04R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x04R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x04R\vtotalTokens\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model*_\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROTOCOL_OPENAI_CHAT\x10\x01\x12\x1f\n" +
	"\x1bPROTOCOL_ANTHROPIC_MESSAGES\x10\x022N\n" +
	"\n" +
	"SynapseHub\x12@\n" +
	"\bRegister\x12\x18.synapse.v1.SakerMessage\x1a\x16.synapse.v1.HubMessage(\x010\x01B6Z4github.com/cinience/saker/proto/synapse/v1;synapsev1b\x06proto3"

var (
	file_proto_synapse_v1_hub_proto_rawDescOnce sync.Once
	file_proto_synapse_v1_hub_proto_rawDescData []byte
)

func file_proto_synapse_v1_hub_proto_rawDescGZIP() []byte {
	file_proto_synapse_v1_hub_proto_rawDescOnce.Do(func() {
		file_proto_synapse_v1_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_synapse_v1_hub_proto_rawDesc), len(file_proto_synapse_v1_hub_proto_rawDesc)))
	})
	return file_proto_synapse_v1_hub_proto_rawDescData
}

var file_proto_synapse_v1_hub_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_synapse_v1_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_synapse_v1_hub_proto_goTypes = []any{
	(Protocol)(0),         // 0: synapse.v1.Protocol
	(*SakerMessage)(nil),  // 1: synapse.v1.SakerMessage
	(*HubMessage)(nil),    // 2: synapse.v1.HubMessage
	(*Hello)(nil),         // 3: synapse.v1.Hello
	(*HelloAck)(nil),      // 4: synapse.v1.HelloAck
	(*Heartbeat)(nil),     // 5: synapse.v1.Heartbeat
	(*ChatRequest)(nil),   // 6: synapse.v1.ChatRequest
	(*CancelRequest)(nil), // 7: synapse.v1.CancelRequest
	(*Shutdown)(nil),      // 8: synapse.v1.Shutdown
	(*Ping)(nil),          // 9: synapse.v1.Ping
	(*Pong)(nil),          // 10: synapse.v1.Pong
	(*ChatChunk)(nil),     // 11: synapse.v1.ChatChunk
	(*ChatDone)(nil),      // 12: synapse.v1.ChatDone
	(*ChatError)(nil),     // 13: synapse.v1.ChatError
	(*ToolEvent)(nil),     // 14: synapse.v1.ToolEvent
	(*Usage)(nil),         // 15: synapse.v1.Usage
	nil,                   // 16: synapse.v1.Hello.LabelsEntry
	nil,                   // 17: synapse.v1.ChatRequest.HeadersEntry
}
var file_proto_synapse_v1_hub_proto_depIdxs = []int32{
	3,  // 0: synapse.v1.SakerMessage.hello:type_name -> synapse.v1.Hello
	5,  // 1: synapse.v1.SakerMessage.heartbeat:type_name -> synapse.v1.Heartbeat
	11, // 2: synapse.v1.SakerMessage.chunk:type_name -> synapse.v1.ChatChunk
	12, // 3: synapse.v1.SakerMessage.done:type_name -> synapse.v1.ChatDone
	13, // 4: synapse.v1.SakerMessage.error:type_name -> synapse.v1.ChatError
	14, // 5: synapse.v1.SakerMessage.tool_event:type_name -> synapse.v1.ToolEvent
	10, // 6: synapse.v1.SakerMessage.pong:type_name -> synapse.v1.Pong
	4,  // 7: synapse.v1.HubMessage.hello_ack:type_name -> synapse.v1.HelloAck
	6,  // 8: synapse.v1.HubMessage.request:type_name -> synapse.v1.ChatRequest
	7,  // 9: synapse.v1.HubMessage.cancel:type_name -> synapse.v1.CancelRequest
	8,  // 10: synapse.v1.HubMessage.shutdown:type_name -> synapse.v1.Shutdown
	9,  // 11: synapse.v1.HubMessage.ping:type_name -> synapse.v1.Ping
	16, // 12: synapse.v1.Hello.labels:type_name -> synapse.v1.Hello.LabelsEntry
	0,  // 13: synapse.v1.Hello.primary_protocol:type_name -> synapse.v1.Protocol
	0,  // 14: synapse.v1.ChatRequest.protocol:type_name -> synapse.v1.Protocol
	17, // 15: synapse.v1.ChatRequest.headers:type_name -> synapse.v1.ChatRequest.HeadersEntry
	15, // 16: synapse.v1.ChatDone.usage:type_name -> synapse.v1.Usage
	1,  // 17: synapse.v1.SynapseHub.Register:input_type -> synapse.v1.SakerMessage
	2,  // 18: synapse.v1.SynapseHub.Register:output_type -> synapse.v1.HubMessage
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_synapse_v1_hub_proto_init() }
func file_proto_synapse_v1_hub_proto_init() {
	if File_proto_synapse_v1_hub_proto != nil {
		return
	}
	file_proto_synapse_v1_hub_proto_msgTypes[0].OneofWrappers = []any{
		(*SakerMessage_Hello)(nil),
		(*SakerMessage_Heartbeat)(nil),
		(*SakerMessage_Chunk)(nil),
		(*SakerMessage_Done)(nil),
		(*SakerMessage_Error)(nil),
		(*SakerMessage_ToolEvent)(nil),
		(*SakerMessage_Pong)(nil),
	}
	file_proto_synapse_v1_hub_proto_msgTypes[1].OneofWrappers = []any{
		(*HubMessage_HelloAck)(nil),
		(*HubMessage_Request)(nil),
		(*HubMessage_Cancel)(nil),
		(*HubMessage_Shutdown)(nil),
		(*HubMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_synapse_v1_hub_proto_rawDesc), len(file_proto_synapse_v1_hub_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_synapse_v1_hub_proto_goTypes,
		DependencyIndexes: file_proto_synapse_v1_hub_proto_depIdxs,
		EnumInfos:         file_proto_synapse_v1_hub_proto_enumTypes,
		MessageInfos:      file_proto_synapse_v1_hub_proto_msgTypes,
	}.Build()
	File_proto_synapse_v1_hub_proto = out.File
	file_proto_synapse_v1_hub_proto_goTypes = nil
	file_proto_synapse_v1_hub_proto_depIdxs = nil
}
