// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/synapse/v1/hub.proto

package synapsev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SynapseHub_Register_FullMethodName = "/synapse.v1.SynapseHub/Register"
)

// SynapseHubClient is the client API for SynapseHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SynapseHubClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SakerMessage, HubMessage], error)
}

type synapseHubClient struct {
	cc grpc.ClientConnInterface
}

func NewSynapseHubClient(cc grpc.ClientConnInterface) SynapseHubClient {
	return &synapseHubClient{cc}
}

func (c *synapseHubClient) Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SakerMessage, HubMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SynapseHub_ServiceDesc.Streams[0], SynapseHub_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SakerMessage, HubMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SynapseHub_RegisterClient = grpc.BidiStreamingClient[SakerMessage, HubMessage]

// SynapseHubServer is the server API for SynapseHub service.
// All implementations must embed UnimplementedSynapseHubServer
// for forward compatibility.
type SynapseHubServer interface {
	Register(grpc.BidiStreamingServer[SakerMessage, HubMessage]) error
	mustEmbedUnimplementedSynapseHubServer()
}

// UnimplementedSynapseHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSynapseHubServer struct{}

func (UnimplementedSynapseHubServer) Register(grpc.BidiStreamingServer[SakerMessage, HubMessage]) error {
	return status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSynapseHubServer) mustEmbedUnimplementedSynapseHubServer() {}
func (UnimplementedSynapseHubServer) testEmbeddedByValue()                    {}

// UnsafeSynapseHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SynapseHubServer will
// result in compilation errors.
type UnsafeSynapseHubServer interface {
	mustEmbedUnimplementedSynapseHubServer()
}

func RegisterSynapseHubServer(s grpc.ServiceRegistrar, srv SynapseHubServer) {
	// If the following call panics, it indicates UnimplementedSynapseHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SynapseHub_ServiceDesc, srv)
}

func _SynapseHub_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SynapseHubServer).Register(&grpc.GenericServerStream[SakerMessage, HubMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SynapseHub_RegisterServer = grpc.BidiStreamingServer[SakerMessage, HubMessage]

// SynapseHub_ServiceDesc is the grpc.ServiceDesc for SynapseHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SynapseHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synapse.v1.SynapseHub",
	HandlerType: (*SynapseHubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _SynapseHub_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/synapse/v1/hub.proto",
}
