package model

import (
	"context"
	"strings"

	"github.com/cinience/saker/pkg/artifact"
)

// ContentBlockType discriminates the kind of content in a ContentBlock.
type ContentBlockType string

const (
	ContentBlockText     ContentBlockType = "text"
	ContentBlockImage    ContentBlockType = "image"
	ContentBlockDocument ContentBlockType = "document"
)

// ContentBlock represents a single piece of content within a message.
// For text blocks only Text is populated. For image/document blocks,
// MediaType and either Data (base64) or URL are set.
type ContentBlock struct {
	Type      ContentBlockType `json:"type"`
	Text      string           `json:"text,omitempty"`
	MediaType string           `json:"media_type,omitempty"` // e.g. "image/jpeg", "application/pdf"
	Data      string           `json:"data,omitempty"`       // base64-encoded content
	URL       string           `json:"url,omitempty"`        // URL source (alternative to Data)
}

// Message represents a single conversational turn.
// Tool calls emitted by the assistant are kept on ToolCalls.
// When ContentBlocks is non-empty it takes precedence over Content for
// multimodal messages (images, documents). Existing text-only callers
// continue to use Content unchanged.
type Message struct {
	Role             string
	Content          string
	ContentBlocks    []ContentBlock // Multimodal content; takes precedence over Content when non-empty
	Artifacts        []artifact.ArtifactRef
	ToolCalls        []ToolCall
	ReasoningContent string // For thinking models (e.g. DeepSeek, Kimi k2.5)
}

// TextContent returns the text portion of the message. When ContentBlocks
// is populated it concatenates all text blocks; otherwise it falls back to
// Content.
func (m Message) TextContent() string {
	if len(m.ContentBlocks) == 0 {
		return m.Content
	}
	var parts []string
	for _, b := range m.ContentBlocks {
		if b.Type == ContentBlockText && b.Text != "" {
			parts = append(parts, b.Text)
		}
	}
	if len(parts) == 0 {
		return m.Content
	}
	return strings.Join(parts, "")
}

// ToolCall captures a function-style invocation generated by the model.
type ToolCall struct {
	ID        string
	Name      string
	Arguments map[string]any
	Result    string // Result stores the execution result for this specific tool call
}

// ToolDefinition describes a callable function exposed to the model.
type ToolDefinition struct {
	Name        string
	Description string
	Parameters  map[string]any
}

// ResponseFormat controls the output format requested from the model.
type ResponseFormat struct {
	Type       string
	JSONSchema *OutputJSONSchema
}

// OutputJSONSchema describes a structured JSON output contract.
type OutputJSONSchema struct {
	Name        string
	Description string
	Schema      map[string]any
	Strict      bool
}

// Request drives a single model completion.
type Request struct {
	Messages []Message
	Tools    []ToolDefinition
	System   string
	// SystemBlocks splits the system prompt into multiple blocks for
	// cache-aware providers. When non-empty, takes precedence over System.
	// Typically: [0] = static (cacheable across sessions), [1] = dynamic.
	SystemBlocks      []string
	Model             string
	SessionID         string
	MaxTokens         int
	Temperature       *float64
	EnablePromptCache bool // Enable prompt caching for system and recent messages
	ResponseFormat    *ResponseFormat

	// --- Optional per-request sampling overrides. Provider adapters
	// consume these when set and ignore them otherwise (so unknown
	// fields never cause an error at the API surface). The OpenAI
	// inbound gateway populates these from the standard request body
	// fields (top_p, stop, seed, tool_choice, parallel_tool_calls).
	TopP              *float64 // nil = provider default
	Stop              []string // nil/empty = no stop sequences set by caller
	Seed              *int64   // nil = no deterministic-seed override
	ToolChoice        string   // "" = no override; "auto"/"none"/specific tool
	ParallelToolCalls *bool    // nil = provider default
}

// Usage reports token accounting for a completion.
type Usage struct {
	InputTokens         int
	OutputTokens        int
	TotalTokens         int
	CacheReadTokens     int
	CacheCreationTokens int
}

// Response wraps the final assistant message and accounting.
type Response struct {
	Message    Message
	Usage      Usage
	StopReason string
}

// StreamResult delivers incremental updates during streaming calls.
type StreamResult struct {
	Delta    string
	ToolCall *ToolCall
	Final    bool
	Response *Response
}

// StreamHandler consumes streaming updates in order.
type StreamHandler func(StreamResult) error

// Model is the provider-agnostic interface used by the agent runtime.
type Model interface {
	Complete(ctx context.Context, req Request) (*Response, error)
	CompleteStream(ctx context.Context, req Request, cb StreamHandler) error
}

// ContextWindowProvider is optionally implemented by Model implementations
// that know their context window size (in tokens).
type ContextWindowProvider interface {
	ContextWindow() int
}

// ModelNamer is optionally implemented by Model implementations that
// expose their configured model name (e.g. "claude-sonnet-4-20250514").
type ModelNamer interface {
	ModelName() string
}
